server:
  port: 8080

database:
  host: "localhost"
  port: 15432
  user: "root"
  password: "123456"
  dbname: "postgres"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

pulsar:
  url: "http://pulsar:8080"
  operation_time_out: 30
  connection_time_out: 30
