server:
  port: 8080

database:
  host: "localhost"
  port: 15432
  user: "root"
  password: "123456"
  dbname: "postgres"

redis:
  host: "localhost"
  port: 16379
  password: ""
  db: 0

pulsar:
  url: "pulsar://localhost:6650"
  operation_time_out: 30
  connection_time_out: 30

log:
  path: "./runtime"